### ISSUE TITLE
Totally random, not actually an issue.

### ISSUE THREAD

**Issue by wowyourclient** [zacharyacutey/zacharyacutey.github.io#1]
Hey Zachary, I had some questions for you about the AP CS exam. I was wondering if you would be available during lunch tomorrow. Just let me know in slack. I will delete the issue, I just didn't know if you check the Nerd Group Slack anymore.

**Comment by zacharyacutey** [comment]
Okay, I'll try to remember!
I'll start coming to Nerd Group again eventually, I just had a lot of other
things.
